### ISSUE TITLE
error: ‘runtime_error’ is not a member of ‘std’

### ISSUE THREAD

**Issue by jokermay** [BenjaminNavarro/open-phri#2]
I followed the basic steps in to have Openphri up and running. But I had some errors in the 'make deploy package=open-phri' step. 

`/home/pid-workspace/packages/open-phri/src/OpenPHRI/utilities/fifth_order_polynomial.cpp:212:9: error: ‘runtime_error’ is not a member of ‘std’
   throw std::runtime_error("In FifthOrderPolynomial::getSecondDerivativeMaximum, rpoly_ak1 failed");
         ^
`
I do not understand why it says that the "'runtime_error' is not a member of 'std'" while I confirm it belongs to. Anyone knows ?

**Comment by BenjaminNavarro** [comment]
Thanks for pointing out this issue. I think I know the problem, it's just strange that I never faced it before.

Can you give me the OS and compiler you're using?

**Comment by jokermay** [comment]
I run it on Ubuntu 14.04 and the C compiler ID is GNU 4.8.4 and CXX compiler GNU 4.8.4.

**Comment by jokermay** [comment]
I run it on Ubuntu 14.04, the C compiler is GNU 4.8.4 and the CXX compiler is GNU 4.8.4.

**Comment by BenjaminNavarro** [comment]
It should be fixed now. Can you try to update the package using `make update package=open-phri` from the `pid-workspace/pid` directory?

**Comment by jokermay** [comment]
I tried and the aforementioned errors were fixed.  But there are other errors like
`/home/joker/pid-workspace/packages/open-phri/src/OpenPHRI/utilities/trajectory_generator.cpp:26:1:   required from here
/usr/include/c++/4.8/bits/shared_ptr_base.h:347:9: error: no match for call to ‘(phri::TrajectoryGenerator<T>::enableErrorTracking(const T*, const T&, bool) [with T = double]::__lambda3) (const double*&)’
       { _M_del._M_del(_M_ptr); }
         ^
`
and 
`In file included from /home/joker/pid-workspace/packages/open-phri/src/OpenPHRI/utilities/trajectory_generator.cpp:20:0:
/home/joker/pid-workspace/packages/open-phri/include/OpenPHRI/OpenPHRI/utilities/trajectory_generator.h:413:60: note: candidates are:
   enableErrorTracking(std::shared_ptr<const T>(reference, [](auto p){}), threshold, recompute_when_resumed);
                                                            ^
In file included from /usr/include/c++/4.8/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/4.8/memory:82,
                 from /home/joker/pid-workspace/packages/open-phri/include/OpenPHRI/OpenPHRI/type_aliases.h:30,
                 from /home/joker/pid-workspace/packages/open-phri/include/OpenPHRI/OpenPHRI/definitions.h:31,
                 from /home/joker/pid-workspace/packages/open-phri/include/OpenPHRI/OpenPHRI/utilities/interpolators_common.h:31,
                 from /home/joker/pid-workspace/packages/open-phri/include/OpenPHRI/OpenPHRI/utilities/trajectory_generator.h:31,
                 from /home/joker/pid-workspace/packages/open-phri/src/OpenPHRI/utilities/trajectory_generator.cpp:20:
/usr/include/c++/4.8/bits/shared_ptr_base.h:483:15: note: void (*)() <conversion>
        __d(__p); // Call _Deleter on __p.
`

**Comment by BenjaminNavarro** [comment]
Ok, I will fix the deployment with Ubuntu 14.04. Currently, it deploys fine with Archlinux and Ubuntu 16.04 (Travis CI). I'll also add the 14.04 to the CI to detect these problems as soon as possible.

**Comment by BenjaminNavarro** [comment]
Ok, it compiles fine for me with a default Ubuntu 14.04 installation so you can try to update the package again and see if it works for you.

**Comment by jokermay** [comment]
Yeah, it compiles fine after I update some of my packages and software of the Ubuntu 14.04. Thanks for your help. It is very kind of you.

**Comment by BenjaminNavarro** [comment]
No problem, a lot of people in robotics community are still using Ubuntu 14.04 so it's important to support it.

Just so you know, the problems came from the default version of Ubuntu not properly (or fully) implementing the C++11 standard.
